version: 1.0.{build}
image: Visual Studio 2019


platform:
    - Any CPU
    #- x86
    #- x64
    #- ARM64
    #- ARM

configuration:
    - Release
    #- Debug

install:
    - ps: >-
        Start-FileDownload 'https://github.com/EWSoftware/SHFB/releases/download/v2019.9.15.0/SHFBInstaller_v2019.9.15.0.zip'

        7z x -y SHFBInstaller_v2019.9.15.0.zip | Out-Null

        Write-Host "Installing MSI..."

        cmd /c start /wait msiexec /i InstallResources\SandcastleHelpFileBuilder.msi /quiet

        Write-Host "Installing VSIX..."

        . "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VSIXInstaller.exe" /q /a InstallResources\SHFBVisualStudioPackage_VS2015AndLater.vsix

        Write-Host "Sandcastle installed" -ForegroundColor Green

build_script:
    - set SHFBROOT=C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - msbuild UsbMonitor.sln /m /verbosity:minimal /t:restore /p:configuration="%configuration%" /p:platform="%platform%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - msbuild UsbMonitor.sln /m /verbosity:minimal  /p:configuration="%configuration%" /p:platform="%platform%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - cd "%APPVEYOR_BUILD_FOLDER%"\Nuget
    - pack.cmd

after_build:
     - cd "%APPVEYOR_BUILD_FOLDER%"
     - ps: >-
        Push-AppveyorArtifact "Nuget\FormsUsbMonitor.2.1.0-beta1.nupkg" -FileName FormsUsbMonitor.2.1.0-beta1.nupkg

        Push-AppveyorArtifact "Nuget\WpfUsbMonitor.2.1.0-beta1.nupkg" -FileName WpfUsbMonitor.2.1.0-beta1.nupkg

        # if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release") {
            # $ZipFileName = "WpfUsbMonitor_$($env:APPVEYOR_REPO_TAG_NAME).zip"
            # 7z a $ZipFileName WpfUsbMonitor\bin\$env:CONFIGURATION\WpfUsbMonitor.dll
        # }

# artifacts:
  # - path: WpfUsbMonitor_*.zip
    # name: releases

# deploy:
    # provider: GitHub
    # auth_token:
        # secure: !!TODO, see https://www.appveyor.com/docs/deployment/github/#provider-settings!!
    # artifact: releases
    # draft: false
    # prerelease: false
    # force_update: true
    # on:
        # appveyor_repo_tag: true
        # configuration: Release
