name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2019
    strategy:
      max-parallel: 2
      matrix:
        build_configuration: [Release, Debug]
        
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Install SHFB
      uses: Bassman2/setup-SHFB@v2
      with:
        version: v2021.4.9.0

    - name: Copy dummy key for signing
      run: |
           Copy-Item  DummySignKey.snk -Destination Src\FormsUsbMonitor60\Bassman.snk
           Copy-Item  DummySignKey.snk -Destination Src\FormsUsbMonitor50\Bassman.snk
           Copy-Item  DummySignKey.snk -Destination Src\FormsUsbMonitorCore31\Bassman.snk
           Copy-Item  DummySignKey.snk -Destination Src\FormsUsbMonitorFramework45\Bassman.snk
           Copy-Item  DummySignKey.snk -Destination Src\WpfUsbMonitor60\Bassman.snk
           Copy-Item  DummySignKey.snk -Destination Src\WpfUsbMonitor50\Bassman.snk
           Copy-Item  DummySignKey.snk -Destination Src\WpfUsbMonitorCore31\Bassman.snk
           Copy-Item  DummySignKey.snk -Destination Src\WpfUsbMonitorFramework45\Bassman.snk

    - name: Nuget restore solution
      run: nuget restore UsbMonitor.sln

    - name: MSBuild of solution
      run: msbuild UsbMonitor.sln /p:configuration="${{ matrix.build_configuration }}" /m /verbosity:minimal

    - name: Nuget pack nuspec
      if: matrix.build_configuration == 'Release'
      working-directory: .\Nuget\
      run: |
           nuget pack FormsUsbMonitor.nuspec -properties Configuration="${{ matrix.build_configuration }}"
           nuget pack WpfUsbMonitor.nuspec -properties Configuration="${{ matrix.build_configuration }}"